name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"
homepage:

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  get_it: ^7.2.0
  melos: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
